### ISSUE TITLE
Create a Android app for Peyar

### ISSUE THREAD

**Issue by mugunth** [thamizha/peyar#1]
Need to create a free android app for peyar.
It could be created as a hybrid app using phonegap. But should be able to run offline.

**Comment by manikk** [comment]
If it would be a hybrid app, we can use it any where... not only on
android. I can start working on it. :)

**Comment by mugunth** [comment]
Sure please start working on it using phonegap.

I experimented with phonegap yesterday, it seems good.
I havent yet tried using tamil characters. If you have time pls check if we
are able to make tamil characters visible either using unicode or TSCII
(dont use any other encoding)

Regards,
Mugunth

On Tue, Jan 10, 2012 at 12:10 PM, Manikk <
reply@reply.github.com

> wrote:
> 
> If it would be a hybrid app, we can use it any where... not only on
> android. I can start working on it. :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thamizha/peyar/issues/1#issuecomment-3424149

## 

Blog: http://mugunth.blogspot.com
Follow me @ http://twitter.com/mugunth

**Comment by mugunth** [comment]
We have created a new project called Arumbu to take care of this. Arumbu will peyar project''s database and will be created using phonegap. It could be packaged for any mobile phone i.e. it could run in android/iphone/windows phone .

So lets close this issue and follow the progress in Arumbu project.
